name: Build and Deploy to ACA

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_SERVER }}.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }} .

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }}
      
      - name: Set ACA secrets referencing Key Vault
        run: |
          az containerapp secret set \
            --name monolithic-clinical-app \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --secrets database-username=@Microsoft.KeyVault(SecretUri=https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-USERNAME) \
                      database-password=@Microsoft.KeyVault(SecretUri=https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-PASSWORD) \
                      database-host=@Microsoft.KeyVault(SecretUri=https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-HOST) \
                      database-port=@Microsoft.KeyVault(SecretUri=https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-PORT) \
                      database-name=@Microsoft.KeyVault(SecretUri=https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-NAME) \
                      jwt-secret=@Microsoft.KeyVault(SecretUri=https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/JWT-SECRET) \
                      account-key-claimmd=@Microsoft.KeyVault(SecretUri=https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/ACCOUNT-KEY-CLAIMMD)
      - name: Deploy Container App with updated config and new image
        run: |
          echo database-username
          az containerapp update \
            --name monolithic-clinical-app \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }} \
            --set-env-vars \
              DATABASE_USERNAME=database-username \
              DATABASE_PASSWORD=database-password \
              DATABASE_HOST=database-host \
              DATABASE_PORT=database-port \
              DATABASE_NAME=database-name \
              JWT_SECRET=jwt-secret \
              ACCOUNT_KEY_CLAIMMD=account-key-claimmd
      #- name: Deploy to ACA
      #   run: |
      #     az containerapp update \
            
      #       --resource-group ${{ secrets.RESOURCE_GROUP }} \
      #       --image ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }} \
      #       --set-env-vars \
      #         DATABASE_USERNAME=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-USERNAME \
      #         DATABASE_PASSWORD=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-PASSWORD \
      #         DATABASE_HOST=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-HOST \
      #         DATABASE_PORT=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-PORT \
      #         DATABASE_NAME=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-NAME \
      #         JWT_SECRET=secretref:${{ secrets.KEYVAULT_NAME }}:JWT-SECRET \
      #         ACCOUNT_KEY_CLAIMMD=secretref:${{ secrets.KEYVAULT_NAME }}:ACCOUNT-KEY-CLAIMMD