name: Build and Deploy to ACA

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_SERVER }}.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }} .

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }}
      
      - name: Create Container App config YAML with Key Vault secrets using User-Assigned Identity
        run: |
          cat <<EOF > containerapp-config.yaml
          secrets:
            - name: database-username
              keyVaultUrl: https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-USERNAME
              identity:
                userAssignedIdentity: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/clinical-app-identity

            - name: database-password
              keyVaultUrl: https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-PASSWORD
              identity:
                userAssignedIdentity: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/clinical-app-identity

            - name: database-host
              keyVaultUrl: https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-HOST
              identity:
                userAssignedIdentity: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/clinical-app-identity

            - name: database-port
              keyVaultUrl: https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-PORT
              identity:
                userAssignedIdentity: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/clinical-app-identity

            - name: database-name
              keyVaultUrl: https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-NAME
              identity:
                userAssignedIdentity: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/clinical-app-identity

            - name: jwt-secret
              keyVaultUrl: https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/JWT-SECRET
              identity:
                userAssignedIdentity: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/clinical-app-identity

            - name: account-key-claimmd
              keyVaultUrl: https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/ACCOUNT-KEY-CLAIMMD
              identity:
                userAssignedIdentity: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/clinical-app-identity

          environmentVariables:
            - name: DATABASE_USERNAME
              secretRef: database-username
            - name: DATABASE_PASSWORD
              secretRef: database-password
            - name: DATABASE_HOST
              secretRef: database-host
            - name: DATABASE_PORT
              secretRef: database-port
            - name: DATABASE_NAME
              secretRef: database-name
            - name: JWT_SECRET
              secretRef: jwt-secret
            - name: ACCOUNT_KEY_CLAIMMD
              secretRef: account-key-claimmd
          EOF

      - name: Deploy Container App with updated config and new image
        run: |
          az containerapp update \
            --name monolithic-clinical-app \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --yaml ./containerapp-config.yaml \
            --image ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }} \
            --set-env-vars \
              DATABASE_USERNAME=database-username \
              DATABASE_PASSWORD=sdatabase-password \
              DATABASE_HOST=database-host \
              DATABASE_PORT=database-port \
              DATABASE_NAME=database-name \
              JWT_SECRET=secretref:jwt-secret \
              ACCOUNT_KEY_CLAIMMD=secretref:account-key-claimmd
      #- name: Deploy to ACA
      #   run: |
      #     az containerapp update \
            
      #       --resource-group ${{ secrets.RESOURCE_GROUP }} \
      #       --image ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }} \
      #       --set-env-vars \
      #         DATABASE_USERNAME=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-USERNAME \
      #         DATABASE_PASSWORD=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-PASSWORD \
      #         DATABASE_HOST=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-HOST \
      #         DATABASE_PORT=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-PORT \
      #         DATABASE_NAME=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-NAME \
      #         JWT_SECRET=secretref:${{ secrets.KEYVAULT_NAME }}:JWT-SECRET \
      #         ACCOUNT_KEY_CLAIMMD=secretref:${{ secrets.KEYVAULT_NAME }}:ACCOUNT-KEY-CLAIMMD