name: Build and Deploy to ACA

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_SERVER }}.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }} .

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }}

      - name: ACA secrets referencing Key Vault
        run: |
          echo "DB_PASSWORD=$(az keyvault secret show --vault-name monoclinicalkeyvault --name DATABASE-PASSWORD --query value -o tsv)" >> $GITHUB_ENV
          echo "DATABASE_USERNAME=$(az keyvault secret show --vault-name monoclinicalkeyvault --name DATABASE-USERNAME --query value -o tsv)" >> $GITHUB_ENV
          echo "DATABASE_HOST=$(az keyvault secret show --vault-name monoclinicalkeyvault --name DATABASE-HOST --query value -o tsv)" >> $GITHUB_ENV
          echo "DATABASE_PORT=$(az keyvault secret show --vault-name monoclinicalkeyvault --name DATABASE-PORT --query value -o tsv)" >> $GITHUB_ENV
          echo "DATABASE_NAME=$(az keyvault secret show --vault-name monoclinicalkeyvault --name DATABASE-NAME --query value -o tsv)" >> $GITHUB_ENV
          echo "JWT_SECRET=$(az keyvault secret show --vault-name monoclinicalkeyvault --name JWT-SECRET --query value -o tsv)" >> $GITHUB_ENV
          echo "ACCOUNT_KEY_CLAIMMD=$(az keyvault secret show --vault-name monoclinicalkeyvault --name ACCOUNT-KEY-CLAIMMD --query value -o tsv)" >> $GITHUB_ENV

      - name: Deploy Container App with updated config and new image
        run: |
          az containerapp update \
            --name monolithic-clinical-app \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }} \
            --set-env-vars \
              DATABASE_USERNAME=$DATABASE_USERNAME \
              DATABASE_PASSWORD=$DB_PASSWORD \
              DATABASE_HOST=$DATABASE_HOST \
              DATABASE_PORT=$DATABASE_PORT \
              DATABASE_NAME=$DATABASE_NAME \
              JWT_SECRET=$JWT_SECRET \
              ACCOUNT_KEY_CLAIMMD=$ACCOUNT_KEY_CLAIMMD