name: Build and Deploy to ACA

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_SERVER }}.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }} .

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }}
      
      - name: Get ACA Managed Identity
        id: get_identity
        run: |
          echo "identity_client_id=$(az containerapp show \
            --name monolithic-clinical-app \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --query identity.principalId -o tsv)" >> $GITHUB_OUTPUT
      - name: Link Key Vault secrets to ACA
        run: |
          az containerapp secret set \
            --name monolithic-clinical-app \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --secrets \
              DATABASE_USERNAME="keyvaultref:https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-USERNAME,identityref:${{ steps.get_identity.outputs.identity_client_id }}" \
              DATABASE_PASSWORD="keyvaultref:https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-PASSWORD,identityref:${{ steps.get_identity.outputs.identity_client_id }}" \
              DATABASE_HOST="keyvaultref:https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-HOST,identityref:${{ steps.get_identity.outputs.identity_client_id }}" \
              DATABASE_PORT="keyvaultref:https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-PORT,identityref:${{ steps.get_identity.outputs.identity_client_id }}" \
              DATABASE_NAME="keyvaultref:https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/DATABASE-NAME,identityref:${{ steps.get_identity.outputs.identity_client_id }}" \
              JWT_SECRET="keyvaultref:https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/JWT-SECRET,identityref:${{ steps.get_identity.outputs.identity_client_id }}" \
              ACCOUNT_KEY_CLAIMMD="keyvaultref:https://${{ secrets.KEYVAULT_NAME }}.vault.azure.net/secrets/ACCOUNT-KEY-CLAIMMD,identityref:${{ steps.get_identity.outputs.identity_client_id }}"

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name monolithic-clinical-app \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }} \
            --set-env-vars \
              DATABASE_USERNAME=DATABASE_USERNAME \
              DATABASE_PASSWORD=DATABASE_PASSWORD \
              DATABASE_HOST=DATABASE_HOST \
              DATABASE_PORT=DATABASE_PORT \
              DATABASE_NAME=DATABASE_NAME \
              JWT_SECRET=JWT_SECRET \
              ACCOUNT_KEY_CLAIMMD=ACCOUNT_KEY_CLAIMMD
      # - name: Deploy to ACA
      #   run: |
      #     az containerapp update \
            
      #       --resource-group ${{ secrets.RESOURCE_GROUP }} \
      #       --image ${{ secrets.REGISTRY_SERVER }}.azurecr.io/monolith-app:${{ github.sha }} \
      #       --set-env-vars \
      #         DATABASE_USERNAME=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-USERNAME \
      #         DATABASE_PASSWORD=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-PASSWORD \
      #         DATABASE_HOST=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-HOST \
      #         DATABASE_PORT=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-PORT \
      #         DATABASE_NAME=secretref:${{ secrets.KEYVAULT_NAME }}:DATABASE-NAME \
      #         JWT_SECRET=secretref:${{ secrets.KEYVAULT_NAME }}:JWT-SECRET \
      #         ACCOUNT_KEY_CLAIMMD=secretref:${{ secrets.KEYVAULT_NAME }}:ACCOUNT-KEY-CLAIMMD